Collate packed sequences
pytorch/opacus pull request #238
Opened 2021-10-29 09:44 UTC by alexandresablayrolles

Support for tuples as well as single tensors

2021-10-31 03:44 UTC, karthikprasad requested changes

2021-10-31 03:44 UTC, karthikprasad commented on opacus/data_loader.py
> +            if type(sample_empty_shapes) is collections.abc.Sequence:
This should be isinstance() instead. 
`type(list()) is collections.abc.Sequence` will return False
`isinstance(list(), collections.abc.Sequence)` will return True

2021-10-31 03:44 UTC, karthikprasad commented on opacus/data_loader.py
> +                return torch.zerso(sample_empty_shapes)
typo: zeros

2021-11-08 13:36 UTC, ffuuugor commented
Do we want to have a test for this, to make sure it works as expected?

2021-11-22 14:17 UTC, alexandresablayrolles commented
Turns out the original code was doing just fine...reverted my changes but still keeping tests in case it's useful.

2021-11-22 15:02 UTC, ffuuugor approved these changes
Yay, more tests!
Please fix flake8 errors before merging

2021-11-23 09:48 UTC, merged