add params check when convert BatchNorm to GroupNorm
pytorch/opacus pull request #390
Opened 2022-03-21 01:08 UTC by XiaobingSuper

This PR will do params check when converting BatchNorm to GroupNorm, because GroupNorm should have some pre-request at its initiation step.

2022-03-21 16:31 UTC, JohnlNguyen commented
Hey, these still fail our unit tests
https://app.circleci.com/pipelines/github/pytorch/opacus/1709/workflows/446de3e4-f2c7-4090-ba3f-7c8793cb680f/jobs/9174

2022-03-22 00:42 UTC, XiaobingSuper commented
@JohnlNguyen , the failed case try to convert **BatchNorm2d(72, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)** to GroupNorm, but it is invalid，how do we ignore this conversion?

2022-03-23 18:04 UTC, karthikprasad requested changes

2022-03-24 01:02 UTC, XiaobingSuper commented on opacus/validators/batch_norm.py
>          min(32, module.num_features), module.num_features, affine=module.affine
Thanks, the code is changed to use the **gcd** method.

2022-03-24 01:46 UTC, karthikprasad approved these changes

2022-03-24 17:34 UTC, gchanan commented on opacus/validators/batch_norm.py
> +            )
what was the previous behavior?  You would get an error message if and only if you actually ran the module?

2022-03-25 00:38 UTC, XiaobingSuper commented on opacus/validators/batch_norm.py
> +            )
@gchanan, yes, you only get an error when running the module before.

2022-03-25 15:13 UTC, closed without merging