Disk
pytorch/opacus pull request #706
Opened 2024-12-23 04:06 UTC by 564612540

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Motivation and Context / Related issue

It introduces a set of new optimizers called DiSK, which uses a simplified Kalman filter to improve optimizer performance.

## How Has This Been Tested (if it applies)

It is tested with the mnist.py from the example folder (with modifications for DiSK) to ensure all the functions work.

## Checklist

Not sure whether to add documents.

- [ ] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

2025-01-08 18:23 UTC, iden-kalemaj approved these changes
Thank you for the contribution! Looks good to me.

2025-01-09 15:25 UTC, iden-kalemaj requested changes
Could you please fix the linting errors here: https://github.com/pytorch/opacus/actions/runs/12486817231/job/35330455867?pr=706.

For more instructions on linting please see the instructions here under "Code style": https://github.com/pytorch/opacus/blob/53b3c25432bb75dd92b22131d02fcdc39c8dbe5f/CONTRIBUTING.md. 

Hopefully, the changes should be minor. Please let us know if there are any questions. Following a unified code style helps us maintain code readability.

2025-01-10 07:37 UTC, 564612540 commented
The error is fixed

2025-01-10 19:48 UTC, iden-kalemaj commented
It seems that there is still an issue with isort. Could you try 
`isort -l 88 --lines-after-imports 2 -m 3 --trailing-comma KFprivacy_engine.py`
It would also be good to run isort individually for each new file contributed, as isort seems to be having issues when run with multiple files simultaneously. 

Apologies for the back and forth.

2025-01-14 21:38 UTC, 564612540 commented
> isort -l 88 --lines-after-imports 2 -m 3 --trailing-comma KFprivacy_engine.py

It is not showing any error from my side when running this command. I don't know what is the issue here.

The logs are:
```
PS D:\Dropbox\Research\Projects\Experiments\Python\opacus\research\disk_optimizer> isort -l 88 --lines-after-imports 2 -m 3 --trailing-comma .\KFprivacy_engine.py -v

                 _                 _
                (_) ___  ___  _ __| |_
                | |/ _/ / _ \/ '__  _/
                | |\__ \/\_\/| |  | |_
                |_|\___/\___/\_/   \_/

      isort your imports, so you don't have to.

                    VERSION 5.11.5

from-type place_module for typing returned STDLIB
from-type place_module for opacus.optimizers returned THIRDPARTY
from-type place_module for opacus.privacy_engine returned THIRDPARTY
from-type place_module for torch returned THIRDPARTY
from-type place_module for optimizers returned FIRSTPARTY
```

2025-01-14 21:53 UTC, iden-kalemaj commented
That is strange. For now, can you please use the following import order in KFprivacy_engine.py:
`
from typing import List, Union

from opacus.optimizers import DPOptimizer
from opacus.privacy_engine import PrivacyEngine
from optimizers import KF_DPOptimizer, get_optimizer_class
from torch import optim


class KF_PrivacyEngine(PrivacyEngine):
`

and re-run black and isort.

2025-01-15 21:15 UTC, 564612540 commented
> That is strange. For now, can you please use the following import order in KFprivacy_engine.py:
> 
> ```
> from typing import List, Union
> 
> from opacus.optimizers import DPOptimizer
> from opacus.privacy_engine import PrivacyEngine
> from optimizers import KF_DPOptimizer, get_optimizer_class
> from torch import optim
> 
> 
> class KF_PrivacyEngine(PrivacyEngine):
> ```
> 
> and re-run black and isort.

isort automatically changes it back to the previous format below:

```
from typing import List, Union

from opacus.optimizers import DPOptimizer
from opacus.privacy_engine import PrivacyEngine
from torch import optim

from optimizers import KF_DPOptimizer, get_optimizer_class


class KF_PrivacyEngine(PrivacyEngine):
```

Now I am changing to 
```
from typing import List, Union

from opacus.optimizers import DPOptimizer
from opacus.privacy_engine import PrivacyEngine
from torch import optim

from .optimizers import KF_DPOptimizer, get_optimizer_class
```

I think this should work

2025-01-15 22:34 UTC, iden-kalemaj approved these changes

2025-01-17 02:52 UTC, closed without merging

2025-01-17 22:50 UTC, iden-kalemaj commented
Thank you again for your contribution. 

We would like to suggest adding copy-right headers to each of the .py files you contributed. The copy-right header would look something like this for an individual contributor

# Copyright (c) FirstName LastName

or

# Copyright (c) CompanyName

if contributing from a company. 

This is for consistentency with files contributed from Meta all of which have copyright headers.